name: epic_free_games
description: get current free games list from epic games page from anywhere
version: 1.0.0
homepage: https://github.com/allanpereira99/epic_free_games

environment:
  sdk: '>=2.18.0 <=3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  http: ^0.13.5
